In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [11]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['friedman_mse','absolute_error','poisson','squared_error'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1144, in wrapper
    estimator._validate_params()
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1144, in wrapper
    estimator._validate_params()
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.78665807 0.7983803  0.77833481 0.80036184
        nan        nan 0.7819483  0.79951583 0.78002181 0.80156017
        nan        nan 0.78244353 0.80077731 0.7790713  0.80245693
        nan        nan 0.78197809 0.80011023 0.79050503 0.80148438]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'absolute_error',
                                       'poisson', 'squared_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [12]:
# print best parameter after tuning 

re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
   
# print classification report 
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}: 0.8692441435892782

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000790,0.000091,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.000702,0.000162,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.052182,0.002348,0.006404,0.000817,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.789263,0.764399,0.844688,0.784654,0.750286,0.786658,0.032239,10
3,0.415342,0.018844,0.021990,0.003665,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.797336,0.764482,0.841524,0.831411,0.757149,0.798380,0.034066,8
4,0.039770,0.001428,0.004673,0.001847,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.792487,0.741268,0.791105,0.813266,0.753548,0.778335,0.026728,16
5,0.415058,0.011785,0.021192,0.002151,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.811247,0.768060,0.832291,0.830619,0.759592,0.800362,0.030851,5
6,0.000730,0.000114,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.000697,0.000092,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.124290,0.005446,0.003996,0.000734,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.772855,0.735536,0.825797,0.812813,0.762741,0.781948,0.033109,13
9,1.223262,0.022516,0.022206,0.003436,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.805058,0.765710,0.840156,0.820933,0.765723,0.799516,0.029752,7
10,0.116068,0.010388,0.003444,0.000301,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.794918,0.745944,0.815889,0.783385,0.759972,0.780022,0.024831,14
11,0.995183,0.239452,0.017361,0.006215,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.796920,0.774389,0.840408,0.829388,0.766695,0.801560,0.029186,2
12,0.000643,0.000048,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.000612,0.000024,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.047525,0.004727,0.006098,0.004234,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.815297,0.741637,0.832894,0.787003,0.735387,0.782444,0.038794,11
15,0.434009,0.013062,0.020721,0.002750,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.804924,0.767364,0.834765,0.837004,0.759830,0.800777,0.032490,4
16,0.043417,0.003421,0.004047,0.001008,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.773043,0.750896,0.819605,0.807952,0.743860,0.779071,0.030157,15
17,0.427059,0.005443,0.020652,0.001619,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.803637,0.777401,0.839849,0.832445,0.758954,0.802457,0.031046,1
18,0.000604,0.000037,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.000604,0.000020,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.042451,0.005291,0.003368,0.000311,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.772710,0.767012,0.808793,0.811271,0.750105,0.781978,0.024095,12
21,0.402148,0.020079,0.020558,0.005139,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.808975,0.762306,0.836350,0.829846,0.763074,0.800110,0.031865,6
22,0.037635,0.003575,0.003514,0.000472,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.805764,0.748015,0.826609,0.819330,0.752807,0.790505,0.033448,9
23,0.381657,0.048031,0.016318,0.003068,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.811770,0.774903,0.833916,0.826833,0.760000,0.801484,0.029078,3

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:23
BMI:23
Children:0
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46224.6245771]