In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [9]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(indep, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
23 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1144, in wrapper
    estimator._validate_params()
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1144, in wrapper
    estimator._validate_params()
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81910333 0.83253214 0.82549177 0.83409281
        nan        nan 0.81852288 0.83527465 0.81601358 0.83371741
        nan        nan 0.81951724 0.83448324 0.81837532 0.8322197
        nan        nan 0.81735754 0.83357458 0.82032737 0.83347954]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
# print best parameter after tuning 

re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001462,0.000460,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002102,0.000317,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.057612,0.003698,0.007031,0.000494,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.848560,0.750293,0.852050,0.818930,0.825685,0.819103,0.036692,12
3,0.520880,0.011001,0.028625,0.002704,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857189,0.780657,0.855809,0.829666,0.839340,0.832532,0.027912,7
4,0.053489,0.004858,0.007693,0.003311,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.854085,0.773782,0.860233,0.817493,0.821866,0.825492,0.030905,9
5,0.518960,0.011790,0.031923,0.002084,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.855483,0.781856,0.864699,0.828756,0.839670,0.834093,0.028922,3
6,0.001959,0.000413,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002642,0.001267,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.060732,0.004656,0.006284,0.000570,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.842975,0.768137,0.837049,0.807331,0.837123,0.818523,0.028111,13
9,0.526413,0.020403,0.026081,0.003600,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861316,0.781499,0.861985,0.831283,0.840289,0.835275,0.029409,1
10,0.055159,0.005688,0.006097,0.001270,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.835777,0.759999,0.837605,0.814894,0.831793,0.816014,0.029136,16
11,0.508366,0.019772,0.030433,0.006377,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858795,0.780247,0.858383,0.829529,0.841633,0.833717,0.028902,4
12,0.002038,0.000911,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001350,0.000095,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.221194,0.005627,0.006662,0.001480,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.860135,0.763848,0.835046,0.811508,0.827049,0.819517,0.031972,11
15,1.703135,0.314644,0.027401,0.009197,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.858660,0.784170,0.858454,0.831347,0.839786,0.834483,0.027307,2
16,0.211938,0.007805,0.006762,0.002453,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.848325,0.758284,0.846453,0.810720,0.828094,0.818375,0.033013,14
17,1.724509,0.304037,0.022182,0.003010,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859508,0.776640,0.856570,0.826291,0.842089,0.832220,0.030197,8
18,0.001211,0.000097,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001142,0.000113,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.063527,0.005347,0.005376,0.000164,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.846882,0.753453,0.846831,0.816501,0.823120,0.817358,0.034229,15
21,0.553139,0.047558,0.030898,0.006030,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.855657,0.775773,0.863683,0.830307,0.842452,0.833575,0.031063,5
22,0.062961,0.007600,0.006763,0.001555,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.843878,0.768158,0.853629,0.818388,0.817583,0.820327,0.029653,10
23,0.600456,0.038229,0.023715,0.002494,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.854286,0.780063,0.864230,0.826570,0.842249,0.833480,0.029517,6

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:34
BMI:23
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[18595.862677]

/Users/mani/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(